{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import astroprov\n",
    "from astropy.io import fits\n",
    "from astropy.io.ascii import SExtractor\n",
    "from astropy.stats import sigma_clipped_stats\n",
    "from astropy.coordinates import SkyCoord\n",
    "import astropy.coordinates as coord\n",
    "\n",
    "import astropy.units as u\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import os\n",
    "from photutils import DAOStarFinder\n",
    "from photutils import CircularAperture\n",
    "from photutils import aperture_photometry\n",
    "#import subproc\n",
    "\n",
    "import numpy as np\n",
    "from astropy import wcs\n",
    "from astropy.io import fits\n",
    "import sys\n",
    "\n",
    "from astroquery.simbad import Simbad\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "from astropy.visualization import SqrtStretch\n",
    "from astropy.visualization.mpl_normalize import ImageNormalize\n",
    "from astropy.table import Table, vstack\n",
    "from astropy.table import Column\n",
    "\n",
    "import collections\n",
    "import subprocess\n",
    "from astropy.io import ascii\n",
    "import time\n",
    "from astropy.utils.data import clear_download_cache"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "clear_download_cache()\n",
    "tabTot =  ascii.read('/home/mj1e16/outTablesImproved/match1mag.csv')\n",
    "Simbad.ROW_LIMIT = 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def segmentSearch(tabTot):\n",
    "\n",
    "    smollTab = tabTot#[start:end]\n",
    "    RA = smollTab['RA']\n",
    "    DEC = smollTab['DEC']\n",
    "    result_table = Simbad.query_region(coord.SkyCoord(ra=RA,dec=DEC,unit=(u.deg,u.deg),frame='fk5'),radius=5*u.arcsec)\n",
    "    #ascii.write(result_table,'/home/mj1e16/outTables/foundObjects_{}_{}.csv'.format(start,end),format='csv',fast_writer=False)\n",
    "    clear_download_cache()\n",
    "    return result_table\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def segmentSearch(tabTot,start,end,bigLength):\n",
    "\n",
    "    smollTab = tabTot[start:end]\n",
    "    RA = smollTab['RA']\n",
    "    DEC = smollTab['DEC']\n",
    "    result_table = Simbad.query_region(coord.SkyCoord(ra=RA,dec=DEC,unit=(u.deg,u.deg),frame='fk5'),radius=5*u.arcsec)\n",
    "    ascii.write(result_table,'/home/mj1e16/outTables/foundObjects_{}_{}.csv'.format(start,end),format='csv',fast_writer=False)\n",
    "    clear_download_cache()\n",
    "    return start\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def segmentSearch(tabTot,start,end,bigLength):\n",
    "\n",
    "    smollTab = tabTot[start:end]\n",
    "    RA = smollTab['RA']\n",
    "    DEC = smollTab['DEC']\n",
    "    result_table = Simbad.query_region(coord.SkyCoord(ra=RA,dec=DEC,unit=(u.deg,u.deg),frame='fk5'),radius=15*u.arcsec)\n",
    "    ascii.write(result_table,'/home/mj1e16/outTables15/foundObjects_{}_{}.csv'.format(start,end),format='csv',fast_writer=False)\n",
    "    clear_download_cache()\n",
    "    return start\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "851\n"
     ]
    }
   ],
   "source": [
    "bigLength = len(tabTot)\n",
    "print(bigLength)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '19:01:14.0394 +38:38:35.5302': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 5 raised an error (recorded in the `errors` attribute of the result table): '18:45:03.0832 +48:05:33.0957': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 7 raised an error (recorded in the `errors` attribute of the result table): '19:01:29.8664 +45:37:14.4378': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 9 raised an error (recorded in the `errors` attribute of the result table): '19:13:53.3925 +43:48:02.942': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 11 raised an error (recorded in the `errors` attribute of the result table): '19:07:10.42 +42:26:46.7694': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 13 raised an error (recorded in the `errors` attribute of the result table): '19:18:33.9045 +47:15:09.8443': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 15 raised an error (recorded in the `errors` attribute of the result table): '19:15:47.2998 +46:02:09.8807': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 17 raised an error (recorded in the `errors` attribute of the result table): '19:27:37.9554 +47:03:30.5898': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 19 raised an error (recorded in the `errors` attribute of the result table): '18:58:44.7238 +42:05:43.5323': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 21 raised an error (recorded in the `errors` attribute of the result table): '18:54:18.952 +46:42:39.802': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 23 raised an error (recorded in the `errors` attribute of the result table): '18:51:08.078 +46:53:15.4808': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 25 raised an error (recorded in the `errors` attribute of the result table): '18:46:25.8346 +47:29:30.7249': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 27 raised an error (recorded in the `errors` attribute of the result table): '18:46:43.0261 +48:23:50.638': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 29 raised an error (recorded in the `errors` attribute of the result table): '19:03:20.8295 +45:50:45.8848': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 31 raised an error (recorded in the `errors` attribute of the result table): '19:04:31.431 +43:36:12.6855': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 33 raised an error (recorded in the `errors` attribute of the result table): '19:08:23.0006 +49:27:21.7671': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 35 raised an error (recorded in the `errors` attribute of the result table): '19:01:49.5206 +48:07:26.7844': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 37 raised an error (recorded in the `errors` attribute of the result table): '19:01:56.7839 +50:02:54.9275': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 39 raised an error (recorded in the `errors` attribute of the result table): '19:23:46.0655 +44:13:31.0416': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 41 raised an error (recorded in the `errors` attribute of the result table): '19:10:05.9258 +50:47:25.7911': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 43 raised an error (recorded in the `errors` attribute of the result table): '18:59:21.0525 +42:30:51.585': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 45 raised an error (recorded in the `errors` attribute of the result table): '18:46:18.7193 +46:29:40.7063': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 47 raised an error (recorded in the `errors` attribute of the result table): '18:45:53.6191 +47:57:50.8779': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 49 raised an error (recorded in the `errors` attribute of the result table): '18:46:17.4403 +48:20:30.062': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 51 raised an error (recorded in the `errors` attribute of the result table): '19:06:07.5681 +44:52:09.5227': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 53 raised an error (recorded in the `errors` attribute of the result table): '18:56:06.1487 +45:47:56.501': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 55 raised an error (recorded in the `errors` attribute of the result table): '19:14:21.2285 +40:41:49.1163': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 57 raised an error (recorded in the `errors` attribute of the result table): '18:46:39.8297 +42:41:01.0501': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 59 raised an error (recorded in the `errors` attribute of the result table): '19:25:41.1881 +44:34:43.9963': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 61 raised an error (recorded in the `errors` attribute of the result table): '19:27:06.6341 +48:06:14.864': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 63 raised an error (recorded in the `errors` attribute of the result table): '19:22:30.2558 +48:12:56.2086': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 65 raised an error (recorded in the `errors` attribute of the result table): '19:44:52.3789 +44:36:25.7024': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 67 raised an error (recorded in the `errors` attribute of the result table): '19:46:09.9627 +47:26:37.2143': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 69 raised an error (recorded in the `errors` attribute of the result table): '18:45:50.9419 +46:35:19.9063': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 71 raised an error (recorded in the `errors` attribute of the result table): '18:44:27.3141 +47:24:37.0168': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 73 raised an error (recorded in the `errors` attribute of the result table): '18:42:38.8126 +47:30:03.6229': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 75 raised an error (recorded in the `errors` attribute of the result table): '18:43:29.353 +47:53:30.249': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 77 raised an error (recorded in the `errors` attribute of the result table): '19:08:54.047 +41:22:09.2381': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 79 raised an error (recorded in the `errors` attribute of the result table): '19:09:29.1672 +49:13:48.9464': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 81 raised an error (recorded in the `errors` attribute of the result table): '19:12:49.0881 +45:38:55.6405': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 83 raised an error (recorded in the `errors` attribute of the result table): '18:42:11.5637 +43:40:48.1315': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 85 raised an error (recorded in the `errors` attribute of the result table): '19:12:34.2786 +50:25:46.9825': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 87 raised an error (recorded in the `errors` attribute of the result table): '19:50:35.7145 +48:42:12.9506': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 89 raised an error (recorded in the `errors` attribute of the result table): '18:53:38.7021 +46:58:51.7989': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 91 raised an error (recorded in the `errors` attribute of the result table): '18:50:56.5295 +46:51:03.1612': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 93 raised an error (recorded in the `errors` attribute of the result table): '18:42:11.1563 +47:34:36.8042': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 95 raised an error (recorded in the `errors` attribute of the result table): '18:50:41.1445 +48:08:00.6404': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 97 raised an error (recorded in the `errors` attribute of the result table): '18:51:28.7274 +43:50:48.7787': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 100 raised an error (recorded in the `errors` attribute of the result table): '19:20:57.4421 +51:44:58.4035': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 102 raised an error (recorded in the `errors` attribute of the result table): '19:19:39.3935 +48:47:29.9031': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 104 raised an error (recorded in the `errors` attribute of the result table): '18:49:51.1347 +46:58:55.241': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 106 raised an error (recorded in the `errors` attribute of the result table): '18:46:13.6069 +48:24:37.9818': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 109 raised an error (recorded in the `errors` attribute of the result table): '18:49:11.9349 +48:30:54.4067': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 111 raised an error (recorded in the `errors` attribute of the result table): '19:05:30.168 +45:37:28.9079': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 113 raised an error (recorded in the `errors` attribute of the result table): '19:05:44.1849 +43:19:04.118': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 115 raised an error (recorded in the `errors` attribute of the result table): '19:02:31.9832 +47:50:16.5709': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 117 raised an error (recorded in the `errors` attribute of the result table): '19:07:05.059 +49:52:14.5029': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 119 raised an error (recorded in the `errors` attribute of the result table): '18:47:24.521 +42:32:48.5958': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 122 raised an error (recorded in the `errors` attribute of the result table): '19:17:46.1968 +49:27:16.5858': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 124 raised an error (recorded in the `errors` attribute of the result table): '18:53:58.7805 +41:33:31.7098': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 126 raised an error (recorded in the `errors` attribute of the result table): '18:42:39.7834 +47:51:26.8109': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 128 raised an error (recorded in the `errors` attribute of the result table): '18:49:52.4479 +48:54:27.5941': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 130 raised an error (recorded in the `errors` attribute of the result table): '18:49:02.462 +48:42:09.7622': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 132 raised an error (recorded in the `errors` attribute of the result table): '18:51:49.978 +45:27:13.4071': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 134 raised an error (recorded in the `errors` attribute of the result table): '19:05:41.7295 +50:42:32.8784': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 136 raised an error (recorded in the `errors` attribute of the result table): '18:48:46.1935 +42:39:36.6623': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 138 raised an error (recorded in the `errors` attribute of the result table): '19:24:52.0419 +45:08:39.9723': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 141 raised an error (recorded in the `errors` attribute of the result table): '19:15:20.2643 +49:53:32.1358': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 143 raised an error (recorded in the `errors` attribute of the result table): '19:22:30.2912 +51:36:37.3201': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 145 raised an error (recorded in the `errors` attribute of the result table): '19:39:05.0715 +49:00:56.5601': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 147 raised an error (recorded in the `errors` attribute of the result table): '18:51:56.768 +46:33:45.3565': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 149 raised an error (recorded in the `errors` attribute of the result table): '18:44:16.3408 +47:55:22.1593': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 151 raised an error (recorded in the `errors` attribute of the result table): '18:50:00.7234 +48:10:55.5767': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 153 raised an error (recorded in the `errors` attribute of the result table): '18:47:14.9064 +48:17:35.4218': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 155 raised an error (recorded in the `errors` attribute of the result table): '19:14:07.6781 +41:10:19.318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 157 raised an error (recorded in the `errors` attribute of the result table): '18:55:57.8572 +49:17:32.0719': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 159 raised an error (recorded in the `errors` attribute of the result table): '19:14:48.4633 +47:23:39.5537': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 162 raised an error (recorded in the `errors` attribute of the result table): '19:11:26.7522 +51:21:55.8938': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 164 raised an error (recorded in the `errors` attribute of the result table): '18:59:44.3882 +41:08:12.6956': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 166 raised an error (recorded in the `errors` attribute of the result table): '19:39:00.8031 +50:38:52.9091': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 168 raised an error (recorded in the `errors` attribute of the result table): '18:56:51.0254 +41:40:05.9566': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 170 raised an error (recorded in the `errors` attribute of the result table): '19:02:31.9135 +41:47:42.5937': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 172 raised an error (recorded in the `errors` attribute of the result table): '18:52:55.2843 +40:50:43.5644': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 174 raised an error (recorded in the `errors` attribute of the result table): '19:42:49.1961 +47:38:26.4803': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 176 raised an error (recorded in the `errors` attribute of the result table): '18:43:35.6294 +43:19:47.8305': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 178 raised an error (recorded in the `errors` attribute of the result table): '19:15:41.9128 +45:45:19.7196': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 180 raised an error (recorded in the `errors` attribute of the result table): '18:49:08.2332 +48:25:54.9463': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 182 raised an error (recorded in the `errors` attribute of the result table): '19:02:39.8442 +48:25:29.1155': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 184 raised an error (recorded in the `errors` attribute of the result table): '19:15:51.3623 +50:05:05.1949': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 186 raised an error (recorded in the `errors` attribute of the result table): '19:00:45.6128 +39:28:33.1212': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 188 raised an error (recorded in the `errors` attribute of the result table): '18:51:32.8339 +41:04:00.3358': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 190 raised an error (recorded in the `errors` attribute of the result table): '18:39:43.9028 +43:21:41.5963': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 192 raised an error (recorded in the `errors` attribute of the result table): '19:03:06.8657 +45:27:25.7102': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 194 raised an error (recorded in the `errors` attribute of the result table): '18:48:21.5361 +47:03:59.327': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 196 raised an error (recorded in the `errors` attribute of the result table): '18:43:27.7513 +47:52:56.4148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 198 raised an error (recorded in the `errors` attribute of the result table): '18:52:22.1761 +48:06:36.0998': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 200 raised an error (recorded in the `errors` attribute of the result table): '19:01:38.9967 +49:28:05.9794': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 203 raised an error (recorded in the `errors` attribute of the result table): '19:11:27.039 +51:18:30.2706': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 205 raised an error (recorded in the `errors` attribute of the result table): '19:17:47.7724 +45:19:39.5016': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 207 raised an error (recorded in the `errors` attribute of the result table): '19:11:03.6423 +40:38:00.0691': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 209 raised an error (recorded in the `errors` attribute of the result table): '19:12:33.1854 +43:14:39.5367': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 211 raised an error (recorded in the `errors` attribute of the result table): '18:44:38.1755 +47:32:41.1213': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 213 raised an error (recorded in the `errors` attribute of the result table): '18:47:47.703 +48:29:02.1808': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 215 raised an error (recorded in the `errors` attribute of the result table): '19:42:46.6867 +50:48:08.2217': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 217 raised an error (recorded in the `errors` attribute of the result table): '19:18:37.2423 +51:42:56.1734': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 219 raised an error (recorded in the `errors` attribute of the result table): '19:02:41.4395 +50:01:58.8394': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 221 raised an error (recorded in the `errors` attribute of the result table): '18:56:40.0623 +44:28:42.2158': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 223 raised an error (recorded in the `errors` attribute of the result table): '18:53:27.3337 +46:29:02.7158': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 225 raised an error (recorded in the `errors` attribute of the result table): '18:56:00.2172 +41:15:47.2546': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 227 raised an error (recorded in the `errors` attribute of the result table): '18:54:49.5329 +43:38:31.074': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 229 raised an error (recorded in the `errors` attribute of the result table): '18:48:08.198 +42:23:36.8524': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 231 raised an error (recorded in the `errors` attribute of the result table): '19:39:16.839 +43:43:07.1345': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 233 raised an error (recorded in the `errors` attribute of the result table): '19:17:22.7222 +50:01:48.8799': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 235 raised an error (recorded in the `errors` attribute of the result table): '19:11:50.7671 +45:31:45.9693': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 237 raised an error (recorded in the `errors` attribute of the result table): '19:07:17.6017 +48:40:24.3226': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 239 raised an error (recorded in the `errors` attribute of the result table): '18:57:58.1426 +48:53:18.248': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 241 raised an error (recorded in the `errors` attribute of the result table): '19:05:56.4589 +42:18:38.0364': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 244 raised an error (recorded in the `errors` attribute of the result table): '18:51:35.7801 +47:09:39.1524': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 246 raised an error (recorded in the `errors` attribute of the result table): '18:45:06.7095 +47:23:16.1857': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 248 raised an error (recorded in the `errors` attribute of the result table): '18:54:26.4256 +41:16:16.4461': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 250 raised an error (recorded in the `errors` attribute of the result table): '18:48:10.862 +44:00:11.2962': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 252 raised an error (recorded in the `errors` attribute of the result table): '18:51:23.4387 +43:56:49.9527': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 254 raised an error (recorded in the `errors` attribute of the result table): '18:51:55.0082 +48:11:02.9698': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 256 raised an error (recorded in the `errors` attribute of the result table): '19:37:49.5385 +50:34:23.1986': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 258 raised an error (recorded in the `errors` attribute of the result table): '19:13:54.6341 +47:55:53.6653': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 260 raised an error (recorded in the `errors` attribute of the result table): '18:49:38.3634 +44:49:44.2201': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 262 raised an error (recorded in the `errors` attribute of the result table): '18:53:07.683 +43:33:52.9434': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 264 raised an error (recorded in the `errors` attribute of the result table): '18:43:18.8959 +43:44:40.471': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 266 raised an error (recorded in the `errors` attribute of the result table): '19:03:56.8283 +43:19:23.0416': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 268 raised an error (recorded in the `errors` attribute of the result table): '18:51:31.5829 +40:49:33.3695': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 270 raised an error (recorded in the `errors` attribute of the result table): '19:04:42.5746 +38:08:01.4653': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 272 raised an error (recorded in the `errors` attribute of the result table): '18:49:28.8002 +46:34:10.7092': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 274 raised an error (recorded in the `errors` attribute of the result table): '19:30:36.546 +49:49:18.8665': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 276 raised an error (recorded in the `errors` attribute of the result table): '19:09:29.3001 +47:06:05.5938': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 278 raised an error (recorded in the `errors` attribute of the result table): '19:05:54.1973 +47:16:14.7832': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 280 raised an error (recorded in the `errors` attribute of the result table): '18:53:28.7076 +43:19:17.5036': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 282 raised an error (recorded in the `errors` attribute of the result table): '19:14:44.3901 +50:47:44.2499': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 284 raised an error (recorded in the `errors` attribute of the result table): '19:20:52.7238 +51:30:44.2497': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 286 raised an error (recorded in the `errors` attribute of the result table): '18:51:16.5124 +47:20:13.4437': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 288 raised an error (recorded in the `errors` attribute of the result table): '18:46:59.345 +48:01:48.5525': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 290 raised an error (recorded in the `errors` attribute of the result table): '18:50:21.499 +48:33:47.6613': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 292 raised an error (recorded in the `errors` attribute of the result table): '19:02:45.7666 +44:02:26.3174': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 294 raised an error (recorded in the `errors` attribute of the result table): '18:49:21.5556 +44:18:28.4949': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 296 raised an error (recorded in the `errors` attribute of the result table): '19:17:39.3865 +49:27:19.3792': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 298 raised an error (recorded in the `errors` attribute of the result table): '18:42:20.5117 +43:48:14.9125': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 300 raised an error (recorded in the `errors` attribute of the result table): '18:41:28.2856 +43:37:14.6952': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 302 raised an error (recorded in the `errors` attribute of the result table): '19:29:24.8472 +44:31:32.766': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 304 raised an error (recorded in the `errors` attribute of the result table): '18:56:22.7566 +40:52:51.8944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 306 raised an error (recorded in the `errors` attribute of the result table): '18:47:45.3955 +48:20:39.3187': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 308 raised an error (recorded in the `errors` attribute of the result table): '19:33:46.9848 +47:43:26.548': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 310 raised an error (recorded in the `errors` attribute of the result table): '19:11:45.7387 +45:37:22.1282': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 312 raised an error (recorded in the `errors` attribute of the result table): '18:51:43.9089 +44:21:22.0545': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 315 raised an error (recorded in the `errors` attribute of the result table): '18:56:52.9756 +47:41:48.0539': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 317 raised an error (recorded in the `errors` attribute of the result table): '18:43:06.6024 +47:10:08.5266': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 319 raised an error (recorded in the `errors` attribute of the result table): '18:47:17.4931 +48:13:43.1143': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 321 raised an error (recorded in the `errors` attribute of the result table): '18:51:35.1088 +42:56:27.0959': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 323 raised an error (recorded in the `errors` attribute of the result table): '19:06:32.7959 +48:07:24.7262': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 325 raised an error (recorded in the `errors` attribute of the result table): '19:07:03.9553 +49:51:54.6423': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 327 raised an error (recorded in the `errors` attribute of the result table): '18:43:16.4493 +42:40:32.7087': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 330 raised an error (recorded in the `errors` attribute of the result table): '19:17:49.1078 +51:59:15.2182': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 332 raised an error (recorded in the `errors` attribute of the result table): '20:05:09.8954 +44:51:03.0709': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 334 raised an error (recorded in the `errors` attribute of the result table): '19:08:48.8233 +38:45:42.0202': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 336 raised an error (recorded in the `errors` attribute of the result table): '18:51:26.1424 +46:11:34.9891': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 338 raised an error (recorded in the `errors` attribute of the result table): '18:51:30.5346 +47:56:28.5788': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 340 raised an error (recorded in the `errors` attribute of the result table): '18:49:30.2293 +48:28:24.7564': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 342 raised an error (recorded in the `errors` attribute of the result table): '19:01:32.367 +46:45:28.5251': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 344 raised an error (recorded in the `errors` attribute of the result table): '19:01:24.7654 +43:08:18.5918': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 346 raised an error (recorded in the `errors` attribute of the result table): '19:10:09.9038 +46:45:21.2657': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 348 raised an error (recorded in the `errors` attribute of the result table): '18:48:09.6965 +42:42:18.498': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 350 raised an error (recorded in the `errors` attribute of the result table): '18:43:13.9097 +42:41:48.5905': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 352 raised an error (recorded in the `errors` attribute of the result table): '18:41:09.1808 +43:07:39.4666': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 355 raised an error (recorded in the `errors` attribute of the result table): '19:24:48.8073 +47:04:37.2782': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 357 raised an error (recorded in the `errors` attribute of the result table): '18:47:06.5426 +48:05:42.4481': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 359 raised an error (recorded in the `errors` attribute of the result table): '18:49:43.0585 +44:03:49.2334': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 361 raised an error (recorded in the `errors` attribute of the result table): '19:12:18.0688 +43:26:34.2646': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 363 raised an error (recorded in the `errors` attribute of the result table): '19:09:33.9832 +41:29:46.5488': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 365 raised an error (recorded in the `errors` attribute of the result table): '18:47:18.5895 +42:34:42.4237': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 367 raised an error (recorded in the `errors` attribute of the result table): '19:29:11.5381 +42:42:10.9196': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 370 raised an error (recorded in the `errors` attribute of the result table): '19:17:56.7609 +51:32:37.4623': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 372 raised an error (recorded in the `errors` attribute of the result table): '19:22:17.1229 +48:26:58.2179': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 374 raised an error (recorded in the `errors` attribute of the result table): '19:11:12.4287 +38:32:43.3452': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 376 raised an error (recorded in the `errors` attribute of the result table): '19:32:52.018 +41:10:02.1258': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 378 raised an error (recorded in the `errors` attribute of the result table): '18:59:42.5264 +40:13:18.9368': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 380 raised an error (recorded in the `errors` attribute of the result table): '19:23:15.5538 +43:23:41.2611': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 382 raised an error (recorded in the `errors` attribute of the result table): '18:46:41.0205 +42:51:08.9515': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 384 raised an error (recorded in the `errors` attribute of the result table): '19:18:07.3894 +46:26:26.4383': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 386 raised an error (recorded in the `errors` attribute of the result table): '18:46:06.1368 +46:42:57.0725': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 388 raised an error (recorded in the `errors` attribute of the result table): '18:48:29.839 +46:12:29.9008': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 390 raised an error (recorded in the `errors` attribute of the result table): '18:49:33.5006 +48:31:46.1592': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 392 raised an error (recorded in the `errors` attribute of the result table): '18:57:15.8155 +49:51:51.307': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 394 raised an error (recorded in the `errors` attribute of the result table): '19:01:20.1762 +50:09:07.6911': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 396 raised an error (recorded in the `errors` attribute of the result table): '19:15:55.0777 +51:18:54.7618': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 398 raised an error (recorded in the `errors` attribute of the result table): '19:08:11.3535 +51:06:11.1173': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 400 raised an error (recorded in the `errors` attribute of the result table): '19:16:43.5348 +39:37:11.938': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 402 raised an error (recorded in the `errors` attribute of the result table): '19:10:32.8486 +44:12:04.6499': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 404 raised an error (recorded in the `errors` attribute of the result table): '18:45:04.5032 +44:16:42.9651': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 406 raised an error (recorded in the `errors` attribute of the result table): '18:43:46.5715 +43:47:25.5081': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 408 raised an error (recorded in the `errors` attribute of the result table): '18:55:29.662 +44:40:25.009': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 410 raised an error (recorded in the `errors` attribute of the result table): '19:36:54.9681 +50:23:32.4715': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 412 raised an error (recorded in the `errors` attribute of the result table): '18:46:52.2548 +47:21:50.8961': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 414 raised an error (recorded in the `errors` attribute of the result table): '19:04:29.954 +49:59:54.9714': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 416 raised an error (recorded in the `errors` attribute of the result table): '19:22:16.2251 +41:21:43.4287': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 418 raised an error (recorded in the `errors` attribute of the result table): '18:49:32.0378 +41:10:42.2635': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 420 raised an error (recorded in the `errors` attribute of the result table): '18:46:19.9379 +44:44:18.0578': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 422 raised an error (recorded in the `errors` attribute of the result table): '18:51:20.3664 +43:03:07.6626': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 424 raised an error (recorded in the `errors` attribute of the result table): '19:03:46.457 +45:17:52.158': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 426 raised an error (recorded in the `errors` attribute of the result table): '18:52:29.7431 +46:54:32.5005': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 428 raised an error (recorded in the `errors` attribute of the result table): '18:47:19.0401 +48:00:54.9692': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 430 raised an error (recorded in the `errors` attribute of the result table): '19:09:39.0288 +49:20:57.156': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 432 raised an error (recorded in the `errors` attribute of the result table): '19:09:32.1181 +48:44:43.4982': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 434 raised an error (recorded in the `errors` attribute of the result table): '19:04:36.2466 +50:41:48.4481': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 436 raised an error (recorded in the `errors` attribute of the result table): '19:12:18.3059 +51:25:38.4816': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 438 raised an error (recorded in the `errors` attribute of the result table): '19:17:43.6264 +50:24:51.842': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 440 raised an error (recorded in the `errors` attribute of the result table): '18:58:24.4959 +48:44:08.6153': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 442 raised an error (recorded in the `errors` attribute of the result table): '19:15:27.9468 +43:23:03.4848': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 444 raised an error (recorded in the `errors` attribute of the result table): '18:50:11.0578 +46:23:17.3444': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 446 raised an error (recorded in the `errors` attribute of the result table): '18:52:10.4106 +48:10:14.3959': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 448 raised an error (recorded in the `errors` attribute of the result table): '18:52:42.8141 +40:40:37.1137': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 450 raised an error (recorded in the `errors` attribute of the result table): '19:20:37.4594 +49:49:00.5148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 452 raised an error (recorded in the `errors` attribute of the result table): '19:21:40.6702 +51:33:28.7013': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 455 raised an error (recorded in the `errors` attribute of the result table): '19:05:39.0783 +46:46:19.0515': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 457 raised an error (recorded in the `errors` attribute of the result table): '19:06:56.0404 +41:44:05.833': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 459 raised an error (recorded in the `errors` attribute of the result table): '18:47:46.4724 +48:08:35.9697': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 461 raised an error (recorded in the `errors` attribute of the result table): '18:58:30.8434 +42:12:58.476': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 463 raised an error (recorded in the `errors` attribute of the result table): '18:44:45.6871 +43:37:33.7422': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 465 raised an error (recorded in the `errors` attribute of the result table): '19:22:32.059 +51:00:12.7977': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 467 raised an error (recorded in the `errors` attribute of the result table): '19:22:13.5493 +50:31:35.9618': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 469 raised an error (recorded in the `errors` attribute of the result table): '19:00:41.6635 +48:22:19.4295': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 471 raised an error (recorded in the `errors` attribute of the result table): '19:03:25.0197 +42:45:32.5479': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 473 raised an error (recorded in the `errors` attribute of the result table): '18:54:01.6083 +46:54:36.2118': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 475 raised an error (recorded in the `errors` attribute of the result table): '19:01:58.6166 +39:42:42.4628': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 477 raised an error (recorded in the `errors` attribute of the result table): '18:44:39.8261 +43:45:42.3868': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 479 raised an error (recorded in the `errors` attribute of the result table): '18:50:49.986 +48:45:10.78': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 481 raised an error (recorded in the `errors` attribute of the result table): '19:07:49.5536 +45:12:04.0856': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 483 raised an error (recorded in the `errors` attribute of the result table): '18:49:21.2562 +44:22:02.7099': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 485 raised an error (recorded in the `errors` attribute of the result table): '18:49:24.0582 +42:27:02.7712': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 487 raised an error (recorded in the `errors` attribute of the result table): '18:42:02.3671 +43:11:40.4169': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 489 raised an error (recorded in the `errors` attribute of the result table): '19:20:45.9013 +51:45:42.2323': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 491 raised an error (recorded in the `errors` attribute of the result table): '18:53:56.0545 +41:16:21.7409': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 493 raised an error (recorded in the `errors` attribute of the result table): '18:53:13.7659 +47:42:12.6649': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 495 raised an error (recorded in the `errors` attribute of the result table): '18:45:35.2511 +47:21:00.7447': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 497 raised an error (recorded in the `errors` attribute of the result table): '18:49:33.1694 +48:25:33.0913': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 499 raised an error (recorded in the `errors` attribute of the result table): '19:21:03.5408 +48:47:40.5989': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 501 raised an error (recorded in the `errors` attribute of the result table): '19:16:20.0984 +47:26:34.233': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 503 raised an error (recorded in the `errors` attribute of the result table): '19:13:58.0396 +49:52:31.6569': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 505 raised an error (recorded in the `errors` attribute of the result table): '18:41:32.6688 +42:58:11.5805': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 507 raised an error (recorded in the `errors` attribute of the result table): '19:01:07.518 +41:40:48.6698': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 509 raised an error (recorded in the `errors` attribute of the result table): '19:05:54.326 +38:06:25.0634': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 511 raised an error (recorded in the `errors` attribute of the result table): '18:56:13.3164 +47:45:29.2403': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 513 raised an error (recorded in the `errors` attribute of the result table): '18:51:58.2092 +47:57:13.3059': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 515 raised an error (recorded in the `errors` attribute of the result table): '18:49:42.9497 +44:36:03.6802': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 517 raised an error (recorded in the `errors` attribute of the result table): '19:04:10.2038 +49:08:12.8633': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 519 raised an error (recorded in the `errors` attribute of the result table): '19:03:56.2636 +50:31:42.3066': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 521 raised an error (recorded in the `errors` attribute of the result table): '18:46:20.183 +42:13:50.8943': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 523 raised an error (recorded in the `errors` attribute of the result table): '18:42:42.1944 +43:59:35.5525': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 525 raised an error (recorded in the `errors` attribute of the result table): '19:35:09.2201 +48:00:17.028': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 528 raised an error (recorded in the `errors` attribute of the result table): '18:50:02.8989 +46:01:18.695': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 530 raised an error (recorded in the `errors` attribute of the result table): '18:47:34.6175 +48:33:46.2108': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 532 raised an error (recorded in the `errors` attribute of the result table): '18:48:40.1971 +45:01:42.4949': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 534 raised an error (recorded in the `errors` attribute of the result table): '18:49:51.8509 +44:17:53.4524': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 536 raised an error (recorded in the `errors` attribute of the result table): '19:07:05.1069 +41:45:27.6023': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 538 raised an error (recorded in the `errors` attribute of the result table): '19:08:18.202 +47:32:48.402': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 540 raised an error (recorded in the `errors` attribute of the result table): '19:33:25.3412 +48:21:29.9859': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 542 raised an error (recorded in the `errors` attribute of the result table): '19:04:05.9887 +39:53:49.0112': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 544 raised an error (recorded in the `errors` attribute of the result table): '18:43:00.4184 +47:47:50.4028': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 546 raised an error (recorded in the `errors` attribute of the result table): '18:51:25.7392 +48:49:44.9137': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 548 raised an error (recorded in the `errors` attribute of the result table): '19:02:34.7929 +44:17:04.2061': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 550 raised an error (recorded in the `errors` attribute of the result table): '18:52:16.7102 +43:10:56.7388': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 552 raised an error (recorded in the `errors` attribute of the result table): '18:40:31.2159 +43:13:31.9408': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 554 raised an error (recorded in the `errors` attribute of the result table): '19:20:23.0708 +51:40:31.1535': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 556 raised an error (recorded in the `errors` attribute of the result table): '19:39:09.4492 +50:12:21.1091': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 558 raised an error (recorded in the `errors` attribute of the result table): '18:55:17.1728 +39:54:05.8244': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 560 raised an error (recorded in the `errors` attribute of the result table): '19:02:50.6096 +43:16:35.8725': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 562 raised an error (recorded in the `errors` attribute of the result table): '18:46:02.9906 +44:03:47.0177': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 564 raised an error (recorded in the `errors` attribute of the result table): '18:47:12.1464 +44:46:07.5562': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 566 raised an error (recorded in the `errors` attribute of the result table): '18:59:29.9892 +45:58:31.9385': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 568 raised an error (recorded in the `errors` attribute of the result table): '19:13:50.9692 +46:14:02.5547': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 570 raised an error (recorded in the `errors` attribute of the result table): '18:54:45.6585 +47:04:52.6148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 572 raised an error (recorded in the `errors` attribute of the result table): '18:46:10.3219 +48:16:03.7331': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 574 raised an error (recorded in the `errors` attribute of the result table): '18:59:06.5411 +48:29:13.47': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 576 raised an error (recorded in the `errors` attribute of the result table): '18:55:19.4289 +49:30:05.7406': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 579 raised an error (recorded in the `errors` attribute of the result table): '18:56:52.3755 +41:58:29.2969': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 581 raised an error (recorded in the `errors` attribute of the result table): '18:49:51.8008 +44:40:46.4973': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 583 raised an error (recorded in the `errors` attribute of the result table): '19:03:50.4043 +46:09:31.6675': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 585 raised an error (recorded in the `errors` attribute of the result table): '18:58:51.1407 +44:46:28.8114': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 587 raised an error (recorded in the `errors` attribute of the result table): '18:50:02.6998 +48:01:51.7626': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 589 raised an error (recorded in the `errors` attribute of the result table): '18:57:34.1232 +49:20:08.2645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 591 raised an error (recorded in the `errors` attribute of the result table): '19:16:35.0055 +51:05:37.3429': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 593 raised an error (recorded in the `errors` attribute of the result table): '19:16:42.9426 +51:15:11.6639': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 595 raised an error (recorded in the `errors` attribute of the result table): '19:03:12.8465 +38:52:04.1973': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 597 raised an error (recorded in the `errors` attribute of the result table): '18:56:08.6817 +40:14:45.7125': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 600 raised an error (recorded in the `errors` attribute of the result table): '18:52:32.1297 +42:41:31.04': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 602 raised an error (recorded in the `errors` attribute of the result table): '18:44:37.3254 +43:00:43.8685': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 604 raised an error (recorded in the `errors` attribute of the result table): '18:42:16.8729 +42:59:52.4705': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 606 raised an error (recorded in the `errors` attribute of the result table): '19:02:59.4634 +45:04:25.5623': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 608 raised an error (recorded in the `errors` attribute of the result table): '19:10:36.69 +46:43:34.7061': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 610 raised an error (recorded in the `errors` attribute of the result table): '18:50:15.317 +48:49:39.1094': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 612 raised an error (recorded in the `errors` attribute of the result table): '19:03:36.4298 +50:13:23.4409': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 614 raised an error (recorded in the `errors` attribute of the result table): '19:12:36.3357 +46:37:42.7507': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 616 raised an error (recorded in the `errors` attribute of the result table): '19:09:03.0882 +48:44:40.6564': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 619 raised an error (recorded in the `errors` attribute of the result table): '18:51:19.3187 +45:20:43.0295': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 621 raised an error (recorded in the `errors` attribute of the result table): '18:43:15.7385 +47:01:45.4637': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 623 raised an error (recorded in the `errors` attribute of the result table): '19:32:36.0424 +47:55:15.1453': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 625 raised an error (recorded in the `errors` attribute of the result table): '19:18:18.7084 +49:47:10.6071': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 627 raised an error (recorded in the `errors` attribute of the result table): '19:14:49.2918 +44:28:16.6531': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 629 raised an error (recorded in the `errors` attribute of the result table): '19:16:43.7574 +47:28:56.9305': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 631 raised an error (recorded in the `errors` attribute of the result table): '18:57:04.8088 +49:36:10.841': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 633 raised an error (recorded in the `errors` attribute of the result table): '19:01:16.3009 +44:12:34.9399': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 635 raised an error (recorded in the `errors` attribute of the result table): '18:49:17.1537 +47:46:44.2979': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 637 raised an error (recorded in the `errors` attribute of the result table): '18:54:55.8361 +40:13:50.9844': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 639 raised an error (recorded in the `errors` attribute of the result table): '18:45:35.3525 +42:41:35.1584': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 641 raised an error (recorded in the `errors` attribute of the result table): '19:23:45.6046 +50:40:06.5862': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 643 raised an error (recorded in the `errors` attribute of the result table): '19:09:26.6154 +51:15:47.4918': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 645 raised an error (recorded in the `errors` attribute of the result table): '19:13:45.6097 +45:46:23.9493': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 647 raised an error (recorded in the `errors` attribute of the result table): '19:03:48.0082 +47:54:40.6513': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 649 raised an error (recorded in the `errors` attribute of the result table): '19:18:50.8866 +41:42:27.1148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 651 raised an error (recorded in the `errors` attribute of the result table): '19:00:45.7157 +46:37:57.6821': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 653 raised an error (recorded in the `errors` attribute of the result table): '18:55:09.6463 +47:26:48.3073': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 655 raised an error (recorded in the `errors` attribute of the result table): '18:48:18.083 +46:02:49.2283': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 657 raised an error (recorded in the `errors` attribute of the result table): '18:48:38.1147 +47:47:21.1279': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 659 raised an error (recorded in the `errors` attribute of the result table): '19:02:24.4983 +41:30:00.9597': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 661 raised an error (recorded in the `errors` attribute of the result table): '18:52:26.0429 +46:41:22.5843': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 663 raised an error (recorded in the `errors` attribute of the result table): '19:38:42.2513 +50:00:24.3203': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 665 raised an error (recorded in the `errors` attribute of the result table): '18:55:42.6429 +45:23:18.229': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 667 raised an error (recorded in the `errors` attribute of the result table): '18:48:22.3731 +42:21:16.7871': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 669 raised an error (recorded in the `errors` attribute of the result table): '19:10:06.2977 +43:54:45.9599': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 671 raised an error (recorded in the `errors` attribute of the result table): '18:43:35.2623 +48:02:33.8158': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 673 raised an error (recorded in the `errors` attribute of the result table): '18:42:00.4066 +47:35:55.8956': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 675 raised an error (recorded in the `errors` attribute of the result table): '18:46:43.5475 +48:23:20.9084': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 677 raised an error (recorded in the `errors` attribute of the result table): '19:31:00.4209 +49:48:44.6287': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 679 raised an error (recorded in the `errors` attribute of the result table): '19:10:59.2933 +47:39:55.8498': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 681 raised an error (recorded in the `errors` attribute of the result table): '18:47:30.4025 +44:33:26.7926': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 683 raised an error (recorded in the `errors` attribute of the result table): '18:53:19.7377 +43:25:33.6048': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 685 raised an error (recorded in the `errors` attribute of the result table): '19:09:39.8101 +41:44:21.7648': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 687 raised an error (recorded in the `errors` attribute of the result table): '19:39:32.482 +44:08:34.7155': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 689 raised an error (recorded in the `errors` attribute of the result table): '18:45:12.2373 +47:03:11.6436': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 691 raised an error (recorded in the `errors` attribute of the result table): '18:43:45.6884 +47:00:18.1092': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 694 raised an error (recorded in the `errors` attribute of the result table): '18:46:31.5569 +43:10:06.0974': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 696 raised an error (recorded in the `errors` attribute of the result table): '19:08:38.2711 +42:02:48.7267': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 698 raised an error (recorded in the `errors` attribute of the result table): '19:20:07.3567 +51:49:34.9734': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 700 raised an error (recorded in the `errors` attribute of the result table): '19:08:44.1617 +38:56:34.8354': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 702 raised an error (recorded in the `errors` attribute of the result table): '18:54:31.7609 +46:50:51.1346': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 704 raised an error (recorded in the `errors` attribute of the result table): '19:01:12.4729 +46:05:24.4785': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 706 raised an error (recorded in the `errors` attribute of the result table): '19:14:45.8453 +43:13:52.8005': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 709 raised an error (recorded in the `errors` attribute of the result table): '19:23:01.0414 +51:06:28.9129': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 712 raised an error (recorded in the `errors` attribute of the result table): '19:25:00.9005 +47:33:54.1771': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 714 raised an error (recorded in the `errors` attribute of the result table): '19:34:38.0286 +44:43:48.3823': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 716 raised an error (recorded in the `errors` attribute of the result table): '18:51:05.8879 +47:14:06.0638': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 718 raised an error (recorded in the `errors` attribute of the result table): '18:48:41.4411 +46:29:45.464': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 720 raised an error (recorded in the `errors` attribute of the result table): '18:59:47.3893 +44:26:19.3488': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 722 raised an error (recorded in the `errors` attribute of the result table): '19:16:33.0764 +42:24:52.6508': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 724 raised an error (recorded in the `errors` attribute of the result table): '19:14:49.4746 +40:18:02.5238': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 726 raised an error (recorded in the `errors` attribute of the result table): '19:01:13.4432 +48:18:56.8474': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 728 raised an error (recorded in the `errors` attribute of the result table): '19:03:57.4135 +50:04:54.1777': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 730 raised an error (recorded in the `errors` attribute of the result table): '18:47:03.4482 +42:34:20.5924': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 733 raised an error (recorded in the `errors` attribute of the result table): '18:41:35.3358 +43:55:13.8306': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 736 raised an error (recorded in the `errors` attribute of the result table): '19:23:13.7872 +51:04:33.3934': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 738 raised an error (recorded in the `errors` attribute of the result table): '19:06:46.4568 +38:33:23.4359': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 740 raised an error (recorded in the `errors` attribute of the result table): '18:50:14.0409 +46:27:56.8175': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 742 raised an error (recorded in the `errors` attribute of the result table): '19:05:51.3014 +48:47:27.171': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 744 raised an error (recorded in the `errors` attribute of the result table): '18:44:12.4175 +42:22:59.8769': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 747 raised an error (recorded in the `errors` attribute of the result table): '19:42:19.6022 +49:45:30.1066': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 749 raised an error (recorded in the `errors` attribute of the result table): '19:05:52.3879 +42:23:35.4055': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 751 raised an error (recorded in the `errors` attribute of the result table): '19:30:25.4033 +46:43:55.1021': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 753 raised an error (recorded in the `errors` attribute of the result table): '18:45:36.0375 +42:48:23.7805': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 755 raised an error (recorded in the `errors` attribute of the result table): '19:11:28.2269 +45:56:34.6948': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 757 raised an error (recorded in the `errors` attribute of the result table): '19:44:55.7884 +49:55:36.4553': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 759 raised an error (recorded in the `errors` attribute of the result table): '18:43:06.6685 +47:39:38.3932': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 761 raised an error (recorded in the `errors` attribute of the result table): '19:03:26.4136 +50:32:56.2787': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 764 raised an error (recorded in the `errors` attribute of the result table): '19:54:27.342 +48:43:28.1539': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 766 raised an error (recorded in the `errors` attribute of the result table): '19:01:29.2932 +45:30:33.8441': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 768 raised an error (recorded in the `errors` attribute of the result table): '18:49:33.0537 +47:56:55.3302': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 770 raised an error (recorded in the `errors` attribute of the result table): '19:01:58.8552 +50:21:38.9793': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 774 raised an error (recorded in the `errors` attribute of the result table): '18:53:45.5774 +42:55:01.0329': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 776 raised an error (recorded in the `errors` attribute of the result table): '18:55:39.9483 +44:35:57.2324': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 778 raised an error (recorded in the `errors` attribute of the result table): '18:51:47.7396 +46:14:08.9808': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 780 raised an error (recorded in the `errors` attribute of the result table): '18:59:02.2909 +49:41:12.9038': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 783 raised an error (recorded in the `errors` attribute of the result table): '19:13:22.0791 +47:58:48.3197': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 785 raised an error (recorded in the `errors` attribute of the result table): '19:06:15.3655 +50:20:16.6337': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 787 raised an error (recorded in the `errors` attribute of the result table): '18:58:56.6636 +43:52:31.2629': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 789 raised an error (recorded in the `errors` attribute of the result table): '18:44:18.7325 +46:46:08.2881': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 791 raised an error (recorded in the `errors` attribute of the result table): '18:47:12.8526 +42:05:26.6154': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 793 raised an error (recorded in the `errors` attribute of the result table): '18:45:27.9776 +43:19:05.6504': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 795 raised an error (recorded in the `errors` attribute of the result table): '19:25:18.5345 +47:53:50.4527': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 798 raised an error (recorded in the `errors` attribute of the result table): '19:06:55.929 +49:27:08.1274': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 801 raised an error (recorded in the `errors` attribute of the result table): '18:52:29.528 +48:11:15.63': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 803 raised an error (recorded in the `errors` attribute of the result table): '19:02:55.9108 +38:00:58.931': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 805 raised an error (recorded in the `errors` attribute of the result table): '18:51:34.3848 +41:48:39.8142': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 807 raised an error (recorded in the `errors` attribute of the result table): '18:48:16.3794 +42:55:57.6759': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 809 raised an error (recorded in the `errors` attribute of the result table): '19:42:44.1493 +45:38:18.594': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 811 raised an error (recorded in the `errors` attribute of the result table): '19:09:58.0177 +47:11:59.6089': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 813 raised an error (recorded in the `errors` attribute of the result table): '18:56:35.9399 +49:16:28.4227': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 815 raised an error (recorded in the `errors` attribute of the result table): '18:52:00.4394 +43:24:25.5705': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 817 raised an error (recorded in the `errors` attribute of the result table): '18:48:40.4572 +42:34:30.689': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 819 raised an error (recorded in the `errors` attribute of the result table): '18:48:03.3899 +46:01:44.3838': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 821 raised an error (recorded in the `errors` attribute of the result table): '19:45:00.1187 +49:52:11.9839': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 823 raised an error (recorded in the `errors` attribute of the result table): '18:48:42.5502 +43:33:54.5953': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 825 raised an error (recorded in the `errors` attribute of the result table): '19:17:27.5982 +44:23:35.853': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 827 raised an error (recorded in the `errors` attribute of the result table): '18:49:40.3365 +46:43:59.3157': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 829 raised an error (recorded in the `errors` attribute of the result table): '19:24:06.3009 +49:07:04.8122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 831 raised an error (recorded in the `errors` attribute of the result table): '19:03:00.7093 +45:44:58.9428': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 833 raised an error (recorded in the `errors` attribute of the result table): '18:54:11.0656 +43:24:23.4035': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 835 raised an error (recorded in the `errors` attribute of the result table): '19:14:57.6658 +44:51:02.0371': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 837 raised an error (recorded in the `errors` attribute of the result table): '19:03:23.9886 +40:43:10.9627': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 839 raised an error (recorded in the `errors` attribute of the result table): '18:52:50.7616 +40:41:38.6328': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 842 raised an error (recorded in the `errors` attribute of the result table): '18:51:56.5803 +48:36:02.1119': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 844 raised an error (recorded in the `errors` attribute of the result table): '18:55:58.3186 +45:18:39.6329': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 846 raised an error (recorded in the `errors` attribute of the result table): '18:51:35.6549 +42:50:42.0174': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 848 raised an error (recorded in the `errors` attribute of the result table): '18:44:08.3128 +43:52:11.8572': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 850 raised an error (recorded in the `errors` attribute of the result table): '19:14:47.6239 +51:45:28.9334': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 852 raised an error (recorded in the `errors` attribute of the result table): '19:02:21.0583 +39:00:21.4604': No astronomical object found :  \n",
      "  (error.line, error.msg))\n"
     ]
    }
   ],
   "source": [
    "tab = segmentSearch(tabTot)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "df = tab.to_pandas()\n",
    "names = df.MAIN_ID.unique().tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: MergeConflictWarning: Cannot merge meta key u'description' types <type 'unicode'> and <type 'unicode'>, choosing description=u'Simbad script executed on 2019.09.26CEST12:40:27' [astropy.utils.metadata]\n",
      "WARNING: MergeConflictWarning: Cannot merge meta key u'description' types <type 'unicode'> and <type 'unicode'>, choosing description=u'Simbad script executed on 2019.09.26CEST12:40:28' [astropy.utils.metadata]\n",
      "WARNING: MergeConflictWarning: Cannot merge meta key u'description' types <type 'unicode'> and <type 'unicode'>, choosing description=u'Simbad script executed on 2019.09.26CEST12:40:29' [astropy.utils.metadata]\n",
      "WARNING: MergeConflictWarning: Cannot merge meta key u'description' types <type 'unicode'> and <type 'unicode'>, choosing description=u'Simbad script executed on 2019.09.26CEST12:40:31' [astropy.utils.metadata]\n"
     ]
    }
   ],
   "source": [
    "customSimbad = Simbad()\n",
    "customSimbad.add_votable_fields('ra(d)','dec(d)','otype','sp')\n",
    "bigtab = []\n",
    "for x in range(len(names)):\n",
    "    smallTab = customSimbad.query_object(names[x])\n",
    "    if len(bigtab) == 0:\n",
    "        bigtab = smallTab\n",
    "    else:\n",
    "        bigtab = vstack([bigtab,smallTab])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/astroquery/simbad/core.py:136: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '19:38:40.1552 +50:27:30.0999': No astronomical object found :\n",
      "  (error.line, error.msg))\n"
     ]
    }
   ],
   "source": [
    "customSimbad = Simbad()\n",
    "customSimbad.add_votable_fields('ra(d)','dec(d)','otype','sp')\n",
    "c = SkyCoord(294.6673134179592, 50.45836108584527,frame='icrs',unit='deg')\n",
    "onetab = customSimbad.query_region(c,radius=10*u.arcsec)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "onetab"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "otypes = bigtab['OTYPE'].tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['DwarfNova', 'Star', 'Star', 'LPV*', 'Mira', 'Mira', 'Mira', 'CataclyV*', 'RotV*', 'DwarfNova', 'DwarfNova', 'CataclyV*']\n"
     ]
    }
   ],
   "source": [
    "print(otypes)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "ename": "MemoryError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mMemoryError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-20-550e013863d5>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mbigtab\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_pandas\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mdf2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdf\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'RA'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m>\u001b[0m\u001b[0;36m285.725\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m&\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdf\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'RA'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m<\u001b[0m \u001b[0;36m285.728\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mdf2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/mj1e16/.local/lib/python2.7/site-packages/astropy/table/table.pyc\u001b[0m in \u001b[0;36mto_pandas\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2702\u001b[0m                     \u001b[0mout\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcolumn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfilled\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnan\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2703\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2704\u001b[0;31m                     \u001b[0mout\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcolumn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mastype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mobject\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfilled\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnan\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2705\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2706\u001b[0m                 \u001b[0mout\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcolumn\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/mj1e16/.local/lib/python2.7/site-packages/astropy/table/column.pyc\u001b[0m in \u001b[0;36m__array_finalize__\u001b[0;34m(self, obj)\u001b[0m\n\u001b[1;32m    352\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    353\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcallable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mBaseColumn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__array_finalize__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 354\u001b[0;31m             \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mBaseColumn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__array_finalize__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    355\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    356\u001b[0m         \u001b[0;31m# Self was created from template (e.g. obj[slice] or (obj * 2))\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/numpy/ma/core.pyc\u001b[0m in \u001b[0;36m__array_finalize__\u001b[0;34m(self, obj)\u001b[0m\n\u001b[1;32m   3017\u001b[0m         \u001b[0;31m# Finalize the fill_value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3018\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_fill_value\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3019\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_fill_value\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_check_fill_value\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_fill_value\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3020\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnames\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3021\u001b[0m             \u001b[0;31m# Finalize the default fill_value for structured arrays\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/mj1e16/miniconda2/envs/astroconda/lib/python2.7/site-packages/numpy/ma/core.pyc\u001b[0m in \u001b[0;36m_check_fill_value\u001b[0;34m(fill_value, ndtype)\u001b[0m\n\u001b[1;32m    472\u001b[0m             \u001b[0;31m# Also in case of converting string arrays.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    473\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 474\u001b[0;31m                 \u001b[0mfill_value\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0marray\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfill_value\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcopy\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mFalse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mndtype\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    475\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mOverflowError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    476\u001b[0m                 \u001b[0;31m# Raise TypeError instead of OverflowError or ValueError.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mMemoryError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "df = bigtab.to_pandas()\n",
    "df2 = df[(df['RA'] >285.725) & [(df['RA'] < 285.728)]]\n",
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "ascii.write(tab,'/home/mj1e16/outTablesImproved/matched15magViz.csv',format='csv',fast_writer=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<bound method Series.unique of 0                      V* V1504 Cyg\n",
       "1           2MASS J18504648+4841181\n",
       "2                      V* V1504 Cyg\n",
       "3                      V* V1504 Cyg\n",
       "4                      V* V1504 Cyg\n",
       "5                      KIC 12055999\n",
       "6                   IRAS 18554+4753\n",
       "7                      V* V1504 Cyg\n",
       "8                      V* V1119 Cyg\n",
       "9                      V* V1119 Cyg\n",
       "10                     V* V1119 Cyg\n",
       "11                     V* V1504 Cyg\n",
       "12                     V* V1453 Cyg\n",
       "13                     V* V1504 Cyg\n",
       "14          2MASS J19293151+3742406\n",
       "15          USNO-B1.0 1360-00297059\n",
       "16                      KIC 8935942\n",
       "17                      V* V585 Lyr\n",
       "18                     V* V1119 Cyg\n",
       "19                      V* V344 Lyr\n",
       "20                     V* V1119 Cyg\n",
       "21                     V* V1119 Cyg\n",
       "22          2MASS J19293151+3742406\n",
       "23                     V* V1504 Cyg\n",
       "24          2MASS J19293151+3742406\n",
       "25                     V* V1504 Cyg\n",
       "26                     KIC 12055999\n",
       "27    MASTER OT J191156.83+403101.6\n",
       "28                     V* V1504 Cyg\n",
       "Name: MAIN_ID, dtype: object>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "names"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "uniqueNames = ['2MASS J18504648+4841181','V* V1504 Cyg','KIC 12055999','IRAS 18554+4753','V* V1119 Cyg','V* V1453 Cyg','2MASS J19293151+3742406','USNO-B1.0 1360-00297059','KIC 8935942','V* V585 Lyr']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'function' object has no attribute 'tolist'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-17-9c51e11be49d>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mnamelist\u001b[0m  \u001b[0;34m=\u001b[0m \u001b[0mnames\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtolist\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m: 'function' object has no attribute 'tolist'"
     ]
    }
   ],
   "source": [
    "namelist  = names.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true,
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "seg = bigLength/1000\n",
    "for x in range(0,1000):\n",
    "    start = x* seg\n",
    "    end = (x+1)*seg\n",
    "    segmentSearch(tabTot,start,end,bigLength)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "dirlist = os.listdir('/home/mj1e16/outTables15/')\n",
    "wrongtabs = []\n",
    "for x in range(len(dirlist)):\n",
    "    if x ==0:\n",
    "        tab = ascii.read('/home/mj1e16/outTables15/'+dirlist[x])\n",
    "    else:\n",
    "        try:\n",
    "            addtab = ascii.read('/home/mj1e16/outTables15/'+dirlist[x])\n",
    "            tab = vstack([tab,addtab])\n",
    "        except:\n",
    "            wrongtabs.append(dirlist[x])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 57,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(wrongtabs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#tabTot =  ascii.read('/home/mj1e16/sextractor/sextractor-master/config/sexdiffOutNew.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "bigLength = len(tab)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "387619\n"
     ]
    }
   ],
   "source": [
    "print(bigLength)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "ascii.write(tab,'/home/mj1e16/outTables15/ds9Matches.csv',format='csv',fast_writer=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "redos = []\n",
    "segs = 1000\n",
    "for x in range(segs):\n",
    "    start = int(x*(bigLength/segs))\n",
    "    end = int((x+1)*(bigLength/segs))\n",
    "    smollTab = tabTot[start:end]\n",
    "    RA = smollTab['RA']\n",
    "    DEC = smollTab['DEC']\n",
    "    if x == 0:\n",
    "        result_table = Simbad.query_region(coord.SkyCoord(ra=RA,dec=DEC,unit=(u.deg,u.deg),frame='fk5'),radius=5*u.arcsec)\n",
    "    else:\n",
    "        #try:\n",
    "        newtab = Simbad.query_region(coord.SkyCoord(ra=RA,dec=DEC,unit=(u.deg,u.deg),frame='fk5'),radius=5*u.arcsec)\n",
    "        result_table = vstack([result_table,newtab])\n",
    "        print('Sucessful',x)\n",
    "#         except ConnectionError:\n",
    "#             print('Failed',x)\n",
    "#             redos.append(x)\n",
    "print('Sucessful: {}'.format(segs-x))\n",
    "print('Failed: {}'.format(x))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "ascii.write(totTab,'sexdiffOut.csv',format='csv',fast_writer=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
